### PR TITLE
Updated dependencies and Helm Chart

### PR DESCRIPTION
**Pull request by michaelsteven**
adding Dockerfile
updating dependencies in build.gradle
adding helm chart
adding kubernetes.md
workaround for db creation in the new starter-data-mongodb

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@michaelsteven Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-samples/cloudfoundry-service-broker&pullRequestId=20)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud-samples/cloudfoundry-service-broker&pullRequestId=20) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@michaelsteven Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-samples/cloudfoundry-service-broker&pullRequestId=20)!

**Comment by scottfrederick** [comment]
@michaelsteven Would you mind squashing these commits down to a smaller set of atomic changes? You can force-push back to the existing branch after doing this to update the PR.

**Comment by michaelsteven** [comment]
Squashed

**Pull request merged**
